pub mod after_process;
pub mod codegen;
mod expression;
mod function;
pub mod generator;
mod inferrence;
mod namer;
pub mod scope;
mod statement;
pub mod summarygen;
mod template;
mod type_check;
pub mod hacking;
